# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [1]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [8]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

What are these functions?

    arange?

In [9]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[4, 8, 9, 4],
         [3, 6, 3, 7],
         [3, 9, 5, 6]],
 
        [[3, 3, 1, 3],
         [3, 9, 2, 2],
         [8, 1, 8, 8]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [10]:
## Arithmetic in arrays is element wise

In [11]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [12]:
c = a-b
c

array([20, 29, 38, 47])

In [13]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [14]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [15]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
a[2:5]

array([ 4,  9, 16])

In [17]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [18]:
b = np.random.randint(1,100,(4,4))

In [24]:
b

array([[83, 96, 12, 32],
       [55, 49, 13, 37],
       [67, 55, 14, 49],
       [31, 95, 44, 30]])

In [25]:
# Guess the output
print(b[2,3])
print(b[0,0])


49
83


In [26]:
b[0:3,1],b[:,1]

(array([96, 49, 55]), array([96, 49, 55, 95]))

In [27]:
b[1:3,:]

array([[55, 49, 13, 37],
       [67, 55, 14, 49]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [30]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [31]:
# Index, columns, underlying numpy data
df.T
df

A         B         C         D
2014-01-01  0.079662 -0.341290  0.084975 -0.669446
2014-01-02 -1.440745  1.723605 -0.946827 -1.334354
2014-01-03 -1.283896  1.165049  0.926230 -0.013107
2014-01-04 -0.610367  0.160735 -1.131547  1.207343
2014-01-05 -1.492739  0.766662 -1.353311  0.918883
2014-01-06  0.583488 -0.530099  0.126303  0.958681

In [32]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [33]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [34]:
df.head()

A         B         C         D
2014-01-01  0.079662 -0.341290  0.084975 -0.669446
2014-01-02 -1.440745  1.723605 -0.946827 -1.334354
2014-01-03 -1.283896  1.165049  0.926230 -0.013107
2014-01-04 -0.610367  0.160735 -1.131547  1.207343
2014-01-05 -1.492739  0.766662 -1.353311  0.918883

In [35]:
df.tail()

A         B         C         D
2014-01-02 -1.440745  1.723605 -0.946827 -1.334354
2014-01-03 -1.283896  1.165049  0.926230 -0.013107
2014-01-04 -0.610367  0.160735 -1.131547  1.207343
2014-01-05 -1.492739  0.766662 -1.353311  0.918883
2014-01-06  0.583488 -0.530099  0.126303  0.958681

In [36]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [42]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.694100  0.490777 -0.382363  0.178000
std    0.869610  0.882505  0.895790  1.025653
min   -1.492739 -0.530099 -1.353311 -1.334354
25%   -1.401533 -0.215784 -1.085367 -0.505361
50%   -0.947132  0.463698 -0.430926  0.452888
75%   -0.092845  1.065452  0.115971  0.948732
max    0.583488  1.723605  0.926230  1.207343

In [88]:
df.sort_values(by='B', inplace=True)

KeyError: 'B'

### Selection

In [47]:
df[['A','B']]

A         B
2014-01-06  0.583488 -0.530099
2014-01-01  0.079662 -0.341290
2014-01-04 -0.610367  0.160735
2014-01-05 -1.492739  0.766662
2014-01-03 -1.283896  1.165049
2014-01-02 -1.440745  1.723605

In [48]:
df[0:3]

A         B         C         D
2014-01-06  0.583488 -0.530099  0.126303  0.958681
2014-01-01  0.079662 -0.341290  0.084975 -0.669446
2014-01-04 -0.610367  0.160735 -1.131547  1.207343

In [ ]:
# multi-axis by label
df.loc[:,['A','B']]

In [ ]:
# Date Range
df.loc['20140102':'20140104',['B']]

In [ ]:
# Fast access to scalar
df.at[dates[1],'B']

In [ ]:
# iloc provides integer locations similar to np style
df.iloc[3:]

### Boolean Indexing

In [50]:
# By label
df.loc[dates[0]]

A    0.079662
B   -0.341290
C    0.084975
D   -0.669446
Name: 2014-01-01 00:00:00, dtype: float64

In [51]:
df[df.A < 0] # Basically a 'where' operation

A         B         C         D
2014-01-04 -0.610367  0.160735 -1.131547  1.207343
2014-01-05 -1.492739  0.766662 -1.353311  0.918883
2014-01-03 -1.283896  1.165049  0.926230 -0.013107
2014-01-02 -1.440745  1.723605 -0.946827 -1.334354

### Setting

In [52]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [54]:
df_posA

A         B         C         D
2014-01-06  0.583488 -0.530099  0.126303  0.958681
2014-01-01  0.079662 -0.341290  0.084975 -0.669446
2014-01-04  0.610367 -0.160735  1.131547 -1.207343
2014-01-05  1.492739 -0.766662  1.353311 -0.918883
2014-01-03  1.283896 -1.165049 -0.926230  0.013107
2014-01-02  1.440745 -1.723605  0.946827  1.334354

In [55]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [56]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [57]:
df['F'] = s1

In [60]:
df

A         B         C         D    F
2014-01-06  0.583488 -0.530099  0.126303  0.958681  5.0
2014-01-01  0.079662 -0.341290  0.084975 -0.669446  NaN
2014-01-04 -0.610367  0.160735 -1.131547  1.207343  3.0
2014-01-05 -1.492739  0.766662 -1.353311  0.918883  4.0
2014-01-03 -1.283896  1.165049  0.926230 -0.013107  2.0
2014-01-02 -1.440745  1.723605 -0.946827 -1.334354  1.0

### Missing Data

In [61]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [62]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [63]:
df1

A         B         C         D    F    E
2014-01-01  0.079662 -0.341290  0.084975 -0.669446  NaN  1.0
2014-01-02 -1.440745  1.723605 -0.946827 -1.334354  1.0  1.0
2014-01-03 -1.283896  1.165049  0.926230 -0.013107  2.0  NaN
2014-01-04 -0.610367  0.160735 -1.131547  1.207343  3.0  NaN

In [64]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

### Operations

In [65]:
df.describe()

A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean  -0.694100  0.490777 -0.382363  0.178000  3.000000
std    0.869610  0.882505  0.895790  1.025653  1.581139
min   -1.492739 -0.530099 -1.353311 -1.334354  1.000000
25%   -1.401533 -0.215784 -1.085367 -0.505361  2.000000
50%   -0.947132  0.463698 -0.430926  0.452888  3.000000
75%   -0.092845  1.065452  0.115971  0.948732  4.000000
max    0.583488  1.723605  0.926230  1.207343  5.000000

In [66]:
df.mean(),df.mean(1) # Operation on two different axes

(A   -0.694100
 B    0.490777
 C   -0.382363
 D    0.178000
 F    3.000000
 dtype: float64, 2014-01-06    1.227675
 2014-01-01   -0.211525
 2014-01-04    0.525233
 2014-01-05    0.567899
 2014-01-03    0.558855
 2014-01-02   -0.199664
 dtype: float64)

### Applying functions

In [67]:
df

A         B         C         D    F
2014-01-06  0.583488 -0.530099  0.126303  0.958681  5.0
2014-01-01  0.079662 -0.341290  0.084975 -0.669446  NaN
2014-01-04 -0.610367  0.160735 -1.131547  1.207343  3.0
2014-01-05 -1.492739  0.766662 -1.353311  0.918883  4.0
2014-01-03 -1.283896  1.165049  0.926230 -0.013107  2.0
2014-01-02 -1.440745  1.723605 -0.946827 -1.334354  1.0

In [68]:
df.apply(np.cumsum)

A         B         C         D     F
2014-01-06  0.583488 -0.530099  0.126303  0.958681   5.0
2014-01-01  0.663150 -0.871390  0.211279  0.289236   NaN
2014-01-04  0.052783 -0.710655 -0.920269  1.496578   8.0
2014-01-05 -1.439956  0.056007 -2.273580  2.415461  12.0
2014-01-03 -2.723852  1.221055 -1.347351  2.402354  14.0
2014-01-02 -4.164597  2.944661 -2.294177  1.068001  15.0

In [69]:
df.apply(lambda x: x.max() - x.min())

A    2.076226
B    2.253705
C    2.279541
D    2.541696
F    4.000000
dtype: float64

In [70]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [76]:
np.random.randn(100,4)

array([[-0.68986405, -1.78416711, -1.16843887,  0.14903457],
       [-1.74138641, -0.71852279, -0.51377391, -1.05772831],
       [-0.8935481 , -0.33205671,  0.78169899, -0.2707525 ],
       [ 1.28002495, -0.0525545 ,  0.66639427,  0.96427312],
       [-0.44777847, -0.27272552,  0.16154517,  0.70800621],
       [-1.33680191,  0.68618653, -0.26743727,  0.83797156],
       [ 1.00460031,  0.94260086,  0.33212907,  0.8977222 ],
       [-0.13126786,  1.18321961,  0.45735749,  0.27736484],
       [ 0.44372597, -0.24698688,  0.95161922, -0.17217026],
       [ 1.28035643, -0.31744494, -1.25983484, -0.06219602],
       [-1.28636717,  0.27601072,  0.56700154, -1.78444311],
       [-0.65034831, -0.61360062,  1.21613089,  0.87918656],
       [-1.25420494,  0.13941232, -0.66737639, -0.49412298],
       [ 0.59481246, -0.26058564,  0.08030095,  0.0077874 ],
       [ 0.32917743, -0.83635311,  1.30575852,  0.93718043],
       [-0.32277441, -0.16708767, -1.79377164,  0.85488815],
       [-0.90159296, -1.

In [79]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0  0.235138  0.008892  0.193625  1.772997
 1  0.228848 -0.818859 -0.378999 -1.534445
 2  0.625964 -1.628042 -0.022359 -0.885118,
           0         1         2         3
 3 -0.605647 -0.022570  1.690131 -0.215359
 4 -2.058419 -0.255117 -0.553312 -1.084565
 5 -1.684367 -0.404127 -0.923055  0.770634
 6 -1.471970 -0.433878 -0.025233  0.431470,
           0         1         2         3
 7  0.907561 -0.157735  0.636332 -1.017058
 8  1.275315  0.069181 -1.899214 -1.057690
 9 -0.962505 -1.197349  2.534912 -0.951254]

In [82]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(5,4))
df

0         1         2         3
0 -0.678225  0.837492 -0.528621  0.336668
1 -0.929720 -0.232040  0.364724  1.278580
2  1.641681  0.867469  0.563876 -0.945474
3 -2.294524 -0.812440 -1.302861  0.108197
4  0.477348 -0.249890  2.643992 -0.042499

In [84]:
pd.concat(pieces)

0         1         2         3
0  0.235138  0.008892  0.193625  1.772997
1  0.228848 -0.818859 -0.378999 -1.534445
2  0.625964 -1.628042 -0.022359 -0.885118
3 -0.605647 -0.022570  1.690131 -0.215359
4 -2.058419 -0.255117 -0.553312 -1.084565
5 -1.684367 -0.404127 -0.923055  0.770634
6 -1.471970 -0.433878 -0.025233  0.431470
7  0.907561 -0.157735  0.636332 -1.017058
8  1.275315  0.069181 -1.899214 -1.057690
9 -0.962505 -1.197349  2.534912 -0.951254

In [85]:
# Also can "Join" and "Append"
df

0         1         2         3
0 -0.678225  0.837492 -0.528621  0.336668
1 -0.929720 -0.232040  0.364724  1.278580
2  1.641681  0.867469  0.563876 -0.945474
3 -2.294524 -0.812440 -1.302861  0.108197
4  0.477348 -0.249890  2.643992 -0.042499

### Grouping


In [89]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [90]:
df

A      B         C         D
0  foo    one  3.199371  1.777441
1  bar    one  1.102813  1.867565
2  foo    two -1.644025  2.258310
3  bar  three -2.445161 -1.489934
4  foo    two -0.663572  0.821422
5  bar    two  0.807518 -0.305525
6  foo    one  0.229813 -0.016666
7  foo  three  0.125175  0.020122

In [91]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one    1.102813  1.867565
    three -2.445161 -1.489934
    two    0.807518 -0.305525
foo one    3.429184  1.760775
    three  0.125175  0.020122
    two   -2.307597  3.079732

### Reshaping

In [92]:
# You can also stack or unstack levels

In [93]:
a = df.groupby(['A','B']).sum()

In [94]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar  1.102813 -2.445161  0.807518  1.867565 -1.489934 -0.305525
foo  1.714592  0.125175 -1.153798  0.880387  0.020122  1.539866

### Time Series


In [95]:
import pandas as pd
import numpy as np

In [96]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [97]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [98]:
ts

2014-01-01 00:00:00    343
2014-01-01 00:00:01    306
2014-01-01 00:00:02     27
2014-01-01 00:00:03    163
2014-01-01 00:00:04     27
2014-01-01 00:00:05     24
2014-01-01 00:00:06    101
2014-01-01 00:00:07    226
2014-01-01 00:00:08    157
2014-01-01 00:00:09    452
2014-01-01 00:00:10     49
2014-01-01 00:00:11    172
2014-01-01 00:00:12     28
2014-01-01 00:00:13     12
2014-01-01 00:00:14    220
2014-01-01 00:00:15    161
2014-01-01 00:00:16    138
2014-01-01 00:00:17    445
2014-01-01 00:00:18    349
2014-01-01 00:00:19    318
2014-01-01 00:00:20    155
2014-01-01 00:00:21    287
2014-01-01 00:00:22    149
2014-01-01 00:00:23    473
2014-01-01 00:00:24    286
2014-01-01 00:00:25     53
2014-01-01 00:00:26    300
2014-01-01 00:00:27    236
2014-01-01 00:00:28     40
2014-01-01 00:00:29     14
                      ... 
2014-01-01 00:01:10    363
2014-01-01 00:01:11    151
2014-01-01 00:01:12    442
2014-01-01 00:01:13    469
2014-01-01 00:01:14    245
2014-01-01 00:01:15    295
2

In [ ]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

In [ ]:
# Many additional time series features
ts. #use tab

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas